package com.chessporg.local_attendance_app.utils.helper

object GeoSourceHelper {
    const val TURF_CALCULATION_FILL_LAYER_GEOJSON_SOURCE_ID =
        "TURF_CALCULATION_FILL_LAYER_GEOJSON_SOURCE_ID"
    const val TURF_CALCULATION_FILL_LAYER_ID = "TURF_CALCULATION_FILL_LAYER_ID"
    const val CIRCLE_CENTER_SOURCE_ID = "CIRCLE_CENTER_SOURCE_ID"
    const val CIRCLE_CENTER_ICON_ID = "CIRCLE_CENTER_ICON_ID"
    const val CIRCLE_CENTER_LAYER_ID = "CIRCLE_CENTER_LAYER_ID"
}